baseURL = "https://hubjet.github.io/photo-gallery/"
languageCode = "en-us"
title = "My Photo Gallery"
theme = "github.com/nicokaiser/hugo-theme-gallery/v4"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

    [params]
  defaultTheme = "dark"
